version: "2"
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./docker/dev/db:/docker-entrypoint-initdb.d:ro

  db-client:
    build: ./docker/dev/db-client
    image: github.com/mariogarcia/bookit-db-client

  neo4j:
    image: neo4j:3.3
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo

  dev:
    build: ./docker/dev
    image: github.com/mariogarcia/bookit-dev
    links:
      - db
      - db-client
      - neo4j
    volumes:
      - $PWD:/home/dev/ws
      - $HOME/.m2:/home/dev/.m2
      - $HOME/.gradle:/home/dev/.gradle
